title: Arber Ecology
remote_theme: mmistakes/minimal-mistakes
plugins: 
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-gist


toc: true
#toc_label: "My Table of Contents" # Optional: overrides default label
toc_icon: "cog"                  # Optional: overrides default Font Awesome icon
toc_sticky: true  



author:
  name   : "Jacob Arber"
  bio    : >-
    I am an Arkansas native and avid naturalist. 
    You can read more about me in the _[About me](/about/)_ section.
  location: "Arkansas, USA"
  github: "jrarber"
  links:
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google-scholar"
      url: "https://scholar.google.com/citations?user=YbJ2SEkAAAAJ&hl=en&oi=ao"
    - label: "iNaturalist"
      icon: "fas fa-fw fa-leaf"
      url: "https://www.inaturalist.org/observations?user_id=jarber"
    #- label: "CV"
    #  icon: "far fa-fw fa-file-pdf"
    #  url: 
