title: Arber Ecology
remote_theme: mmistakes/minimal-mistakes
plugins: 
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-gist

author:
  name   : "Jacob Arber"
  bio    : >-
    I am an Arkansas native and avid naturalist. 
    You can read more about me in the [About me](/about/) section.
  location: "Arkansas, USA"
  github: "jrarber"
  links:
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google-scholar"
      url: "https://scholar.google.com/citations?user=YbJ2SEkAAAAJ&hl=en&oi=ao"
    #- label: "CV"
    #  icon: "far fa-fw fa-file-pdf"
    #  url: 
