title: Arber Ecology
remote_theme: mmistakes/minimal-mistakes
plugins: 
  - jekyll-remote-theme
  - jekyll-include-cache

author:
  name   : "Jacob Arber"
  bio    : >-
    I am an Arkansas native and avid naturalist. 
    You can read more about me in the [About me](/about/) section.
  location: "Arkansas, USA"
  github: "jrarber"
  links:
    
